"use client";
import React from 'react'
import Image from 'next/image'
import { Button } from '@/components/ui/button'
import { LayoutDashboard, Shield, UserCircle } from 'lucide-react'
import { usePathname } from 'next/navigation'
import { Progress } from "@/components/ui/progress"

import Link from 'next/link'

function SideBar() {
  const MenuList = [
    {
      name: 'Dashboard',
      icon: LayoutDashboard,
      path: '/dashboard'
    },
    {
      name: 'Upgrade',
      icon: Shield,
      path: '/dashboard/upgrade'
    },
    {
      name: 'Profile',
      icon: UserCircle,
      path: '/dashboard/profile'
    },
  ]
  const path = usePathname();

  return (
    <div className='h-screen p-5 flex flex-col'>
      <div className='flex items-center gap-2 mb-10'>
        <Image src={'/logo.svg'} alt='logo' width={40} height={40} style={{ width: 'auto', height: 'auto' }} />
        <h2 className="font-bold text-2xl text-white tracking-tight">Study Buddy</h2>
      </div>

      <div className='flex-1'>
        <Link href={'/create'} className='w-full'>
          <Button className="w-full text-lg rounded-full py-6 bg-white text-black hover:bg-slate-200 transition-all font-bold">
            + Create New
          </Button>
        </Link>
        <div className='mt-8'>
          {MenuList.map((menu, index) => (
            <Link href={menu.path} key={index}>
              <div className={`flex gap-4 items-center p-3 mt-2 rounded-full cursor-pointer transition-all ${path === menu.path ? 'bg-white/10 text-white font-semibold' : 'text-slate-400 hover:text-white hover:bg-white/5'}`}>
                <menu.icon className="w-5 h-5" />
                <h2 className="text-lg">{menu.name}</h2>
              </div>
            </Link>
          ))}
        </div>
      </div>

      <div className='pt-5'>
        <div className='bg-white/5 p-6 rounded-3xl border border-white/10'>
          <h2 className='text-sm font-semibold text-white mb-2'>Available Credits</h2>
          <Progress value={60} className="h-1.5 mb-3 bg-white/10 [&>div]:bg-white" />
          <h2 className='text-xs text-slate-400 mb-4'>3 Out of 5 Credits Used</h2>
          <Link href={'/dashboard/upgrade'}>
            <Button variant="outline" className="w-full rounded-full border-white/20 text-white hover:bg-white hover:text-black transition-all font-bold">
              Upgrade Now
            </Button>
          </Link>
        </div>
        <p className='text-[10px] text-slate-500 text-center mt-6 uppercase tracking-widest font-medium'>Generated by AI</p>
      </div>
    </div>
  )
}

export default SideBar